installer:
  image: andreaskoch/dockerized-magento-installer
  environment:
    DOMAIN: dockerized-magento.local
    MAGENTO_ROOT: /var/www/html/web
    MYSQL_HOST: mysql
    MYSQL_DATABASE: magento
    MYSQL_USER: root
    MYSQL_PASSWORD: pw
    ADMIN_USERNAME: admin
    ADMIN_FIRSTNAME: Admin
    ADMIN_LASTNAME: Inistrator
    ADMIN_PASSWORD: password123
    ADMIN_FRONTNAME: admin
    ADMIN_EMAIL: admin@example.com
    ENCRYPTIONKEY: 731aea833710535779fe8c7c49bc6c4d
  volumes_from:
    - nginx
  volumes:
    - /code/dockerized-magento/config/installer/php/php.ini:/usr/local/etc/php/php.ini
    - /code/dockerized-magento/config/installer/magerun/n98-magerun.yaml.tmpl:/etc/n98-magerun.yaml.tmpl
    - /code/dockerized-magento/config/installer/magento/local.xml.tmpl:/etc/local.xml.tmpl
    - /code/dockerized-magento/config/installer/magento/fpc.xml.tmpl:/etc/fpc.xml.tmpl
    - /code/dockerized-magento/config/installer/bin/substitute-env-vars.sh:/bin/substitute-env-vars.sh
    - /code/dockerized-magento/config/installer/bin/install.sh:/bin/install.sh
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "solr:solr"
    - "mysql:mysql"
  entrypoint: /bin/install.sh

nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes:
    - /code/dockerized-magento/logs/nginx:/var/log/nginx
    - /code/dockerized-magento/config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
    - /code/dockerized-magento/config/ssl/cert.key:/etc/nginx/ssl/cert.key
    - /code/dockerized-magento/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - /code/dockerized-magento/config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
    - /code/dockerized-magento/config/nginx/includes:/etc/nginx/includes
    - /code/dockerized-magento/config/nginx/custom-locations:/etc/nginx/custom-locations
  volumes_from:
    - php
php:
  image: andreaskoch/dockerized-magento-php
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "solr:solr"
    - "mysql:mysql"
  volumes:
    - /code/dockerized-magento:/var/www/html
mysql:
  image: mysql:5.5
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: pw
  volumes:
    - ./data/mysql:/var/lib/mysql
solr:
  image: andreaskoch/dockerized-magento-solr
cache:
  image: redis:latest
fullpagecache:
  image: redis:latest
sessions:
  image: redis:latest
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8080:80"
  links:
    - "mysql:mysql"
  environment:
    PMA_HOST: "mysql"
    PMA_PORT: 3306
